# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Update version
      run: |
        sed -i 's@{{VERSION}}@'"${{ steps.get_version.outputs.VERSION }}"'@' setup.py
        sed -i 's@{{VERSION}}@'"${{ steps.get_version.outputs.VERSION }}"'@' docker/requirements-docker.txt

    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*

    - name: Build and publish docker image
      env:
        DOCKER_USERNAME: MatTerra
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        DOCKER_REPO: docker.pkg.github.com
        DOCKER_IMAGE: novaweb-mobi/connexion-api-docker/novaapi
        DOCKER_TAG: ${{ steps.get_version.outputs.VERSION }}
      run: |
        docker login $DOCKER_REPO -u $DOCKER_USERNAME -p$DOCKER_PASSWORD
        docker build -t $DOCKER_REPO/$DOCKER_IMAGE:$DOCKER_TAG -f docker/Dockerfile docker/
        docker push $DOCKER_REPO/$DOCKER_IMAGE:$DOCKER_TAG
